### ISSUE TITLE
onUndo throws exception on undo action after card retirement

### ISSUE THREAD

**Issue by mosteli** [mass-immersion-approach/MIARetirementAddon#10] opened 2019-11-09 15:10 UTC
#### Nature of issue?

- Found a bug

It looks like the onUndo function does not always handle the case where a card was just retired.

#### Details about the bug: 

- Operating System: Windows 10
- Steps to reproduce this bug: 
1. Review card until it gets retired
2. After popup about card getting retired is displayed, undo the previous review action. (ctrl+z)

```
Anki 2.1.14 (7b93e985) Python 3.6.7 Qt 5.12.1 PyQt 5.11.3
Platform: Windows 10
Flags: frz=True ao=True sv=1

Caught exception:
  File "aqt\main.py", line 814, in onUndo
  File "C:\Users\Eli\AppData\Roaming\Anki2\addons21\1666520655\main.py", line 339, in miaRetUndo
    ogUndo(mw.col)
  File "anki\collection.py", line 673, in undo
  File "C:\Users\Eli\AppData\Roaming\Anki2\addons21\1666520655\main.py", line 313, in miaRetUndoReview
    moveToDeck(c.retirementActions[1], [c.id])
<class 'TypeError'>: moveToDeck() takes 1 positional argument but 2 were given
```

**Comment by LucasMIA** [comment] 2020-01-09 17:16
I believe this issue has been fixed with the latest commit, I have already pushed it to AnkiWeb. Please try it and let me know, I only ask that you also try it because someone on Discord has reported that the issue still occurs after updating through AnkiWeb.

**Comment by LucasMIA** [comment] 2020-01-12 20:31
This issue seems to be confirmed fixed.

**Closed as completed by LucasMIA** 2020-01-12 20:31 UTC
