### ISSUE TITLE
Using undo will jump to a random card

### ISSUE THREAD

**Issue by hgiesel** [mass-immersion-approach/MIARetirementAddon#9] opened 2019-10-19 22:12 UTC
#### Nature of issue

- Found a bug

#### Details about the bug: 

- Operating System: macOS v10.15, Anki v2.1.15
- Steps to reproduce this bug:

Use undo feature during review. It won't show you the last card, but rather a random card from all current due cards.

**Comment by LucasMIA** [comment] 2019-11-01 17:31
I am fairly certain the undo feature in Anki already jumps back to a random card as it is.

**Comment by heitorvrb** [comment] 2019-11-04 12:29
I can confirm that disabling the addon makes CTRL+Z work correctly again.

With the addon disabled, you fail a card and press CTRL+Z then it goes back to the same card.

With the addon enabled, you fail a card and press CTRL+Z then it goes to a random due card.

**Comment by hgiesel** [comment] 2019-11-04 13:43
Yes. Since I've disabled this addon two weeks ago, it goes back to the same card again, like it used to.

**Comment by edoreld** [comment] 2019-11-08 12:08
I can confirm that this is happening as well on my Anki (2.1.16) 

It would be great to have a solution.

**Comment by robertkaucher** [comment] 2019-12-02 18:00
I have tested this on a Mac that did not have the add-on installed. I used COMMAND+Z and it returned to the previously reviewed card. I then installed the the add on and tested it again and the keyboard shortcut no longer works. Using the undo button in the menu bar does still work as expected so this is only an issue with the keyboard shortcut.

**Comment by LucasMIA** [comment] 2020-01-09 17:12
I believe this issue has been fixed with the latest commit, I have already pushed it to AnkiWeb, can you guys confirm whether it is fixed, and if so I will close this issue. Sorry that it took so long, was busy with other projects. I only ask that you also try it because someone on Discord has reported that the issue still occurs after updating through AnkiWeb.

**Comment by LucasMIA** [comment] 2020-01-12 20:31
This issue seems to be confirmed fixed.

**Closed as completed by LucasMIA** 2020-01-12 20:31 UTC
